### ISSUE TITLE
1.5.1 and later are (again) in violation of the PoDoFo License

### ISSUE THREAD

**Issue by rnhmjoj** [M0Rf30/cie-middleware-linux#100]
https://github.com/M0Rf30/cie-middleware-linux/commit/bc5d3d4929263024c1a46affa01c92ed5c0c187f undoes the main point of this fork, at least for me. I can no longer distribute cie-middleware-linux in Nixpkgs without violating the LGPL.

**Comment by M0Rf30** [comment]
Yeah I understand. At least you should just use podofo-vanilla branch with broken PaDES signature (PDF graphical signature)

**Comment by rnhmjoj** [comment]
> Yeah I understand. Maybe you didn't notice the podofo-vanilla branch.

It looked out of date, so I'm essentially reverting that commit with a patch from the main release.

> Are you able to confirm that podofo-vanilla branch fixes compilation on macOS (related to DWORD)?

Not yet, the build on darwin is still manually disabled, but I'm planning on getting a volunteer to test it.

**Comment by M0Rf30** [comment]
Closed because a podofo-vanilla branch is provided, with broken pdf signature

**Comment by M0Rf30** [comment]
Starting from 1.5.8 cie-middleware-linux supports vanilla 0.10.4 with working document signing. `main` branch is now the only development branch
🎉
