### ISSUE TITLE
L'abbinamento della carta fallisce con le versioni > 1.5.1

### ISSUE THREAD

**Issue by rcasta74** [M0Rf30/cie-middleware-linux#107]
Sto compilando la libreria su rpi5 (aarch64) togliendo la parte di codice riguardante la firma digitale; usando l'applicativo java eseguendo l'abbinamento ottengo il seguente errore:
```
2024-08-17 16:18:20.367  [E] Errore inaspettato durante la comunicazione con la smart card
```
Riprovando l'abbinamento poi il programma crasha con:
```
# Problematic frame:
# C  [libcrypto.so.3+0x1f91b0]  EVP_DigestUpdate+0x10
```

Provando ad usare [abilitacie.cpp](https://raw.githubusercontent.com/opensignature/cie-pkcs11/main/abilitacie.cpp) ottengo invece il seguente errore:
```
2024-08-17 16:18:20:313  [ERROR] VerificaSOD - SOD sign not valid
2024-08-17 16:18:20:363  [ERROR] AbbinaCIE - Exception VerificaSOD - SOD sign not valid
```
Stessi errori se provo a compilare la libreria per intero usando il branch `podofo-vanilla`

Il problema sembra essere stato introdotto con il commit 2f8654d1
Compilando la libreria al commit precedente, l'abbinamento funziona sia con il programma java sia con quello cpp.

**Comment by M0Rf30** [comment]
CIao, è stato segnalato un errore relativo al mancato abbinamento e risolto con questo commit
https://github.com/M0Rf30/cie-middleware-linux/commit/b98d0d6ea1b2382780292d03958eef3cfc80a64e

Puoi confermarmi che hai provato gli ultimi commit?

**Comment by rcasta74** [comment]
> Puoi confermarmi che hai provato gli ultimi commit?

Confermo: ho riprovato di nuovo ora includendo anche il merge della mia PR :)

> Il branch podofo-vanilla disabilita solo la firma grafica sui pdf ed elimina gli header custom di podofo, dovrebbe già fare al caso tuo.

L' ho provato giusto per un ulteriore test, ma non dovrebbe cambiare nulla se compilo la libreria escludendo il codice relativo alla sign-sdk

> Perchè, inoltre, dovrei prestare attenzione o usare abilitacie.cpp di opensignature? Non l'ho capito.

L' applicativo java stampa un generico messaggio di errore, mentre con abilitacie.cpp ho esattamente il messaggio dell'eccezione che viene triggerata nella libreria.

Appena ho un po' di tempo provo ad analizzare le modifiche nel commit 2f8654d che nel mio caso `e quello che ha introdotto l'errore

**Comment by rcasta74** [comment]
Confermo comunque l'errore anche con l'applicativo java, abilitando a debug i log della libreria:
```
2024-08-19 12:25:16:878  [INFO] AbbinaCIE - Verifying SOD, digest algorithm: RSA/SHA256
2024-08-19 12:25:16:880  [ERROR] VerificaSOD - SOD sign not valid
2024-08-19 12:25:16:931  [ERROR] AbbinaCIE - Exception VerificaSOD - SOD sign not valid
```
Inoltre la carta viene riconosciuta come:
```
2024-08-19 12:25:13:439  [INFO] ReadCIEType - cie_type() CIE Gemalto detected
```

**Comment by rcasta74** [comment]
Ho provato a revertare il commit 2f8654d ed a riapplicare le modifiche un po' per volta, sono arrivato alla conclusione che il mio problema `e dovuto alle modifiche in questi file:
```
libs/shared/src/Crypto/MD5.cpp
libs/shared/src/Crypto/MD5.h
libs/shared/src/Crypto/SHA1.cpp
libs/shared/src/Crypto/SHA1.h
libs/shared/src/Crypto/SHA256.cpp
libs/shared/src/Crypto/sha256.h
```
Revertando queste modifiche l'abbinamento funziona.
Nei prossimi giorni provo a capire il motivo per cui non funzionano nel mio caso; forse dipende dall'architettura o dalla distro.

**Comment by M0Rf30** [comment]
> Ho provato a revertare il commit [2f8654d](https://github.com/M0Rf30/cie-middleware-linux/commit/2f8654d1fcf0f887fcdb362c3af4293a0afc7773) ed a riapplicare le modifiche un po' per volta, sono arrivato alla conclusione che il mio problema `e dovuto alle modifiche in questi file:
> 
> ```
> libs/shared/src/Crypto/MD5.cpp
> libs/shared/src/Crypto/MD5.h
> libs/shared/src/Crypto/SHA1.cpp
> libs/shared/src/Crypto/SHA1.h
> libs/shared/src/Crypto/SHA256.cpp
> libs/shared/src/Crypto/sha256.h
> ```
> 
> Revertando queste modifiche l'abbinamento funziona. Nei prossimi giorni provo a capire il motivo per cui non funzionano nel mio caso; forse dipende dall'architettura o dalla distro.

Intanto grazie per l'impegno. Giusto per curiosità: puoi elencare distro usata e versioni librerie? In particolare openssl e quelle di crittografia? Sono abbastanza impegnato in questi giorni per analizzare il problema, confido in una PR da parte tua o nei giorni che verranno

**Comment by rcasta74** [comment]
distro: [iArmtix Linux](https://armtixlinux.org/) (una derivata di Arch Linux che non usa systemd)
openssl: 3.3.1-1
crypto++: 8.9.0-1

Nei giorni scorsi non ho avuto tempo di fare ulteriori analisi; aggiorno questa issue non appena trovo qualcosa.

**Comment by rcasta74** [comment]
Ciao, sono tornato ad analizzare il problema e penso di aver individuato l'errore, ma non capisco perche' l'errore non impatta anche altri.

Nel file `libs/shared/src/Crypto/SHA1.cpp` e simili il metodo `Init()`   e' definito in questo modo
```
void CSHA1::Init() {
  EVP_MD_CTX* ctx = EVP_MD_CTX_new();
  EVP_DigestInit_ex(ctx, EVP_sha1(), NULL);
  isInit = true;
}
```
quindi viene definito ed inizializzato un puntatore locale ctx, invece di inizializzare la variabile ctx definita nel file .h
Nei metodi `Update()` e `Final()` viene invece utilizzata la variabile globale ctx che non risulta quindi inizializzata.

Se applico la seguente patch l'abbinamento della carta torna a funzionare:
```
--- a/libs/shared/src/Crypto/MD5.cpp	2024-11-05 22:40:55.000000000 +0100
+++ b/libs/shared/src/Crypto/MD5.cpp	2024-12-03 14:35:12.635146398 +0100
@@ -8,7 +8,7 @@
 
 void CMD5::Init() {
   // throw logged_error("Un'operazione di hash � gi� in corso");
-  EVP_MD_CTX* ctx = EVP_MD_CTX_new();
+  ctx = EVP_MD_CTX_new();
   EVP_DigestInit_ex(ctx, EVP_md5(), NULL);
   isInit = true;
 }
--- a/libs/shared/src/Crypto/SHA1.cpp	2024-11-05 22:40:55.000000000 +0100
+++ b/libs/shared/src/Crypto/SHA1.cpp	2024-12-03 14:34:28.466732668 +0100
@@ -7,7 +7,7 @@
 CSHA1::~CSHA1() {}
 
 void CSHA1::Init() {
-  EVP_MD_CTX* ctx = EVP_MD_CTX_new();
+  ctx = EVP_MD_CTX_new();
   EVP_DigestInit_ex(ctx, EVP_sha1(), NULL);
   isInit = true;
 }
--- a/libs/shared/src/Crypto/SHA256.cpp	2024-11-05 22:40:55.000000000 +0100
+++ b/libs/shared/src/Crypto/SHA256.cpp	2024-12-03 14:34:59.375022135 +0100
@@ -6,7 +6,7 @@
 #include <openssl/evp.h>
 
 void CSHA256::Init() {
-  EVP_MD_CTX* ctx = EVP_MD_CTX_new();
+  ctx = EVP_MD_CTX_new();
   EVP_DigestInit_ex(ctx, EVP_sha256(), NULL);
   isInit = true;
 }
```

Non apro una PR con la patch in quanto non capisco perche' nessun altro ha lo stesso problema.
