### ISSUE TITLE
Fix all implicit type conversions

### ISSUE THREAD

**Issue by rnhmjoj** [M0Rf30/cie-middleware-linux#22]
Besides a variety of other warnings, there are *a lot* of type narrowing and type conversions in the libcie-pkcs11 C++ project.
These are not just GCC poking fun at C++ developers, if you're building with clang some become errors and in some platforms others are actually broken code. See for example a Darwin build [here](https://gist.githubusercontent.com/rnhmjoj/2cfae83e0fe38e5b2e7d653d11f36a21/raw/849402d4745c7b857850a24872f40ec4e9aaa4b3/gistfile1.txt), where `DWORD` is `unsigned int`, not `unsigned long` as implicitly assumed.

Being a Java application and a native library with just a handful of universal libraries for dependencies, I'm pretty sure this project could actually work on a lot more platforms than just GNU/Linux distro if these issues could be fixed.

**Comment by M0Rf30** [comment]
Can you try with latest commits? I managed to fix some issues here and there for clang.
On my machine I can build the library with clang 14

**Comment by rnhmjoj** [comment]
Thanks, I can confirm it builds with clang on x86_64 and aarch64 Linux.
There remains the DWORD issue in SCardListReaders (and probably other functions).

**Comment by M0Rf30** [comment]
This
https://github.com/M0Rf30/cie-middleware-linux/commit/17fd24bf265fca19b423ed622038a27d39c73c9f
should fix issues on macOS
